### ISSUE TITLE
Navigation timeout of 30000 ms exceeded

### ISSUE THREAD

**Issue by shivansh-narayan** [shihabmridha/educative.io-downloader#5]
I am getting this error after Processing batch of lessons.

![image](https://user-images.githubusercontent.com/34347884/78382225-1c91ab00-75f4-11ea-830f-eab5bb80e700.png)

**Comment by shihabmridha** [comment]
**Background:**
What happens is, the script fetches a batch of 4/5 lesson URLs then opens 4/5 separate tabs then load each URL to each tab and wait for 30000ms for each tab to load the full page. If any page does not load fully in 30000ms then it throws that timeout error and proceeds for the next batch. So, you can say network connectivity is the reason here.

**Possible solution**:
Open the **_app.ts_** file and check **_line 17_** and increase the value of `HTTP_REQUEST_TIMEOUT` from **_30000_** to something larger.
