### ISSUE TITLE
Images are not shown

### ISSUE THREAD

**Issue by mod-ali** [shihabmridha/educative.io-downloader#83]
![Untitled](https://github.com/shihabmridha/educative.io-downloader/assets/45165138/cb434c98-5c92-4d01-b001-92820718cb35)

**Comment by shihabmridha** [comment]
It happened mostly because of slow internet. When it saved the page, the images were not loaded yet. 
Go to [this line](https://github.com/shihabmridha/educative.io-downloader/blob/45524dc83046a692ef4666942c34815c2651432b/src/download.ts#L59C27-L59C27) and increase the value from `3000` to something bigger. Then compile the project and run it again.

**Comment by shihabmridha** [comment]
Resolving due to inactivity.
